import type {
  Profile,
  Company,
  University,
  Internship,
  Application,
  Interview,
  Placement,
  InternshipReport,
  Evaluation,
  CareerPassportProfile,
  Notification,
  AuditLog,
} from '@/lib/types';

export const initialData = {
  profiles: [
    {
      id: 'usr_student_01',
      email: 'kamga.david@univ-yaounde1.cm',
      full_name: 'David Kamga',
      avatar_url: null,
      role: 'student' as const,
      sub_role: null,
      phone: '+237 671 234 567',
      bio: 'BSc Software Engineering student at University of Yaoundé I. Passionate about Next.js, Cloud Architectures, and Full-Stack Engineering.',
      status: 'active' as const,
      created_at: '2026-01-10T08:00:00Z',
      updated_at: '2026-02-15T14:30:00Z',
    },
    {
      id: 'usr_company_01',
      email: 'brenda.ngu@mtn.cm',
      full_name: 'Brenda Ngu',
      avatar_url: null,
      role: 'company' as const,
      sub_role: 'HR & Talent Acquisition Lead',
      phone: '+237 670 998 877',
      bio: 'Enterprise Talent Lead at MTN Cameroon Douala Headquarters.',
      status: 'active' as const,
      created_at: '2025-11-05T09:00:00Z',
      updated_at: '2026-01-20T11:00:00Z',
    },
    {
      id: 'usr_university_01',
      email: 'tchinda.paul@enspy.cm',
      full_name: 'Dr. Paul Tchinda',
      avatar_url: null,
      role: 'university' as const,
      sub_role: 'Director of Academic Internships',
      phone: '+237 699 112 233',
      bio: 'Academic internship director at National Advanced School of Engineering (ENSPY), Yaoundé.',
      status: 'active' as const,
      created_at: '2025-10-15T10:00:00Z',
      updated_at: '2026-02-01T09:00:00Z',
    },
    {
      id: 'usr_supervisor_01',
      email: 'fon.martin@camtel.cm',
      full_name: 'Eng. Martin Fon',
      avatar_url: null,
      role: 'supervisor' as const,
      sub_role: 'Principal Cloud & DevOps Architect',
      phone: '+237 677 445 566',
      bio: 'Industry supervisor mentoring interns in Cloud Systems, Kubernetes, and Data Center operations at CAMTEL.',
      status: 'active' as const,
      created_at: '2025-12-01T12:00:00Z',
      updated_at: '2026-02-10T16:00:00Z',
    },
    {
      id: 'usr_admin_01',
      email: 'tessohmanuel@gmail.com',
      full_name: 'Manuel Tessoh (Admin)',
      avatar_url: null,
      role: 'admin' as const,
      sub_role: 'super_admin',
      phone: '+237 650 921 917',
      bio: 'ManTech Nexus Chief Executive Administrator.',
      status: 'active' as const,
      created_at: '2025-09-01T00:00:00Z',
      updated_at: '2026-03-01T00:00:00Z',
    },
  ] as Profile[],

  companies: [
    {
      id: 'comp_01',
      name: 'MTN Cameroon',
      slug: 'mtn-cameroon',
      industry: 'Telecommunications & Digital Services',
      description:
        'Leading telecommunications and digital fintech solutions provider connecting millions across Cameroon.',
      website: 'https://www.mtn.cm',
      email: 'careers@mtn.cm',
      phone: '+237 670 000 000',
      logo_url: null,
      region: 'Littoral',
      city: 'Douala',
      address: 'Boulevard de la Liberté, Akwa, Douala',
      size: '500+',
      verification_status: 'verified' as const,
      created_at: '2025-10-01T00:00:00Z',
      updated_at: '2026-01-15T00:00:00Z',
    },
    {
      id: 'comp_02',
      name: 'Orange Cameroun',
      slug: 'orange-cameroun',
      industry: 'Telecommunications & Cloud Services',
      description:
        'Multinational telecom operator offering cloud computing, cybersecurity, mobile finance, and connectivity.',
      website: 'https://www.orange.cm',
      email: 'recrutement@orange.cm',
      phone: '+237 699 000 000',
      logo_url: null,
      region: 'Littoral',
      city: 'Douala',
      address: 'Boulevard de la République, Douala',
      size: '500+',
      verification_status: 'verified' as const,
      created_at: '2025-10-05T00:00:00Z',
      updated_at: '2026-01-18T00:00:00Z',
    },
    {
      id: 'comp_03',
      name: 'CAMTEL (Cameroon Telecommunications)',
      slug: 'camtel',
      industry: 'National Telecom & National Fiber Backbone',
      description:
        'The incumbent national telecommunications operator managing subsea cable landings and national datacenters.',
      website: 'https://www.camtel.cm',
      email: 'contact@camtel.cm',
      phone: '+237 222 234 065',
      logo_url: null,
      region: 'Centre',
      city: 'Yaoundé',
      address: 'Boulevard du 20 Mai, Yaoundé',
      size: '500+',
      verification_status: 'verified' as const,
      created_at: '2025-10-10T00:00:00Z',
      updated_at: '2026-01-22T00:00:00Z',
    },
    {
      id: 'comp_04',
      name: 'ActiveSpaces Tech Innovation Hub',
      slug: 'activespaces',
      industry: 'Software Engineering & Tech Incubator',
      description:
        'Pioneering Cameroonian tech hub cultivating software engineering startups, cloud architectures, and digital talents.',
      website: 'https://www.activespaces.com',
      email: 'info@activespaces.com',
      phone: '+237 675 112 233',
      logo_url: null,
      region: 'Littoral',
      city: 'Douala',
      address: 'Akwa Silicon Hub, Douala',
      size: '11-50',
      verification_status: 'verified' as const,
      created_at: '2025-11-01T00:00:00Z',
      updated_at: '2026-02-05T00:00:00Z',
    },
    {
      id: 'comp_05',
      name: 'Silicon Mountain Buea Labs',
      slug: 'silicon-mountain-buea',
      industry: 'Software Engineering & AI/ML',
      description:
        'Renowned software ecosystem in Buea, Southwest Region, specializing in mobile applications, AI systems, and SaaS.',
      website: 'https://siliconmountain.cm',
      email: 'contact@siliconmountain.cm',
      phone: '+237 677 889 900',
      logo_url: null,
      region: 'South-West',
      city: 'Buea',
      address: 'Molyko Silicon Valley Avenue, Buea',
      size: '51-200',
      verification_status: 'verified' as const,
      created_at: '2025-11-15T00:00:00Z',
      updated_at: '2026-02-10T00:00:00Z',
    },
  ] as Company[],

  universities: [
    {
      id: 'univ_01',
      name: 'University of Yaoundé I',
      slug: 'university-of-yaounde-1',
      type: 'Public State University',
      description:
        'The mother university of Cameroon, hosting renowned Computer Science, Applied Mathematics, and Technology departments.',
      website: 'https://www.uy1.uninet.cm',
      email: 'contact@uy1.uninet.cm',
      phone: '+237 222 221 320',
      logo_url: null,
      region: 'Centre',
      city: 'Yaoundé',
      address: 'Ngoa-Ekélé, Yaoundé',
      verification_status: 'verified' as const,
      created_at: '2025-09-15T00:00:00Z',
      updated_at: '2026-01-10T00:00:00Z',
    },
    {
      id: 'univ_02',
      name: 'University of Buea',
      slug: 'university-of-buea',
      type: 'Anglo-Saxon State University',
      description:
        'Premier Anglo-Saxon university known for the Faculty of Engineering and Technology (FET) powering Silicon Mountain.',
      website: 'https://www.ubuea.cm',
      email: 'info@ubuea.cm',
      phone: '+237 233 322 134',
      logo_url: null,
      region: 'South-West',
      city: 'Buea',
      address: 'Molyko, Buea',
      verification_status: 'verified' as const,
      created_at: '2025-09-20T00:00:00Z',
      updated_at: '2026-01-12T00:00:00Z',
    },
    {
      id: 'univ_03',
      name: 'National Advanced School of Engineering (ENSPY)',
      slug: 'enspy-yaounde',
      type: 'Polytechnic Engineering Grande École',
      description:
        'Cameroon’s premier polytechnic institution training elite Computer Engineers, Telecom Architects, and Industrial Computing specialists.',
      website: 'https://www.polytechnique.cm',
      email: 'direction@polytechnique.cm',
      phone: '+237 222 231 226',
      logo_url: null,
      region: 'Centre',
      city: 'Yaoundé',
      address: 'Melong, Yaoundé',
      verification_status: 'verified' as const,
      created_at: '2025-09-25T00:00:00Z',
      updated_at: '2026-01-14T00:00:00Z',
    },
  ] as University[],

  internships: [
    {
      id: 'int_01',
      company_id: 'comp_01',
      title: 'Full-Stack Software Engineering Intern',
      slug: 'full-stack-software-engineering-intern-mtn',
      field_of_study_id: 'fld_se',
      specialization: 'Next.js, TypeScript & PostgreSQL Cloud Systems',
      description:
        'Join the digital enterprise engineering division at MTN Cameroon. You will design, build, and deploy production microservices, secure REST/GraphQL APIs, and high-performance React/Next.js client portals serving enterprise operations.',
      department: 'Digital Solutions & Enterprise Architecture',
      education_level: 'HND / BSc / BEng in Software Engineering or Computer Science',
      region: 'Littoral',
      city: 'Douala',
      location: 'MTN Tech Center, Akwa',
      work_mode: 'hybrid' as const,
      duration_months: 6,
      start_date: '2026-10-15',
      end_date: '2027-04-15',
      deadline: '2026-10-05T23:59:59Z',
      is_paid: true,
      allowance_xaf: 150000,
      positions_available: 4,
      application_method: 'mantech' as const,
      application_url: null,
      instructions: 'Submit your portfolio, CV, and university enrollment proof directly via ManTech Nexus.',
      contact_email: 'digital.interns@mtn.cm',
      is_featured: true,
      moderation_status: 'published' as const,
      created_at: '2026-08-01T00:00:00Z',
      updated_at: '2026-09-10T00:00:00Z',
      skills: ['TypeScript', 'Next.js', 'PostgreSQL', 'Prisma', 'REST API', 'Docker'],
      requirements: [
        'Currently enrolled in Year 2+ of HND, BSc or Master in Software Engineering',
        'Demonstrated experience with modern TypeScript and component-based UI',
        'Understanding of SQL databases and API design patterns',
        'Strong analytical and collaborative problem-solving skills',
      ],
      company: {
        id: 'comp_01',
        name: 'MTN Cameroon',
        slug: 'mtn-cameroon',
        logo_url: null,
        verification_status: 'verified',
        city: 'Douala',
        region: 'Littoral',
      },
    },
    {
      id: 'int_02',
      company_id: 'comp_02',
      title: 'Cybersecurity & Threat Detection Intern',
      slug: 'cybersecurity-threat-detection-intern-orange',
      field_of_study_id: 'fld_cyber',
      specialization: 'SOC Analysis, Vulnerability Scanning & Identity Governance',
      description:
        'Collaborate with the Orange CyberDefense team in Douala to monitor security telemetry, triage SIEM alerts, perform vulnerability assessments, and implement zero-trust access controls across telecommunications infrastructure.',
      department: 'CyberDefense & Information Security',
      education_level: 'BSc / Master in Cybersecurity or Computer Networks',
      region: 'Littoral',
      city: 'Douala',
      location: 'Orange Headquarters, Douala',
      work_mode: 'on-site' as const,
      duration_months: 4,
      start_date: '2026-11-01',
      end_date: '2027-02-28',
      deadline: '2026-10-15T23:59:59Z',
      is_paid: true,
      allowance_xaf: 135000,
      positions_available: 2,
      application_method: 'mantech' as const,
      application_url: null,
      instructions: 'Complete application on ManTech Nexus including your security project write-up.',
      contact_email: 'cyber.recrutement@orange.cm',
      is_featured: true,
      moderation_status: 'published' as const,
      created_at: '2026-08-10T00:00:00Z',
      updated_at: '2026-09-12T00:00:00Z',
      skills: ['Network Security', 'SIEM', 'Linux', 'Python', 'Wireshark', 'IAM'],
      requirements: [
        'Solid foundation in TCP/IP, OSI model, and firewalls',
        'Experience with Linux command line and security auditing tools',
        'Familiarity with OWASP Top 10 vulnerabilities',
      ],
      company: {
        id: 'comp_02',
        name: 'Orange Cameroun',
        slug: 'orange-cameroun',
        logo_url: null,
        verification_status: 'verified',
        city: 'Douala',
        region: 'Littoral',
      },
    },
    {
      id: 'int_03',
      company_id: 'comp_03',
      title: 'Cloud DevOps & Fiber Infrastructure Intern',
      slug: 'cloud-devops-infrastructure-intern-camtel',
      field_of_study_id: 'fld_cloud',
      specialization: 'Kubernetes, Linux System Administration & Fiber Backbone',
      description:
        'Contribute to the management of national data centers at CAMTEL Yaoundé. Gain hands-on exposure to cloud hypervisors, automated CI/CD pipelines, container orchestration, and high-availability network routing.',
      department: 'National Datacenter & Infrastructure Operations',
      education_level: 'HND / BEng in Computer Networks or Cloud Systems',
      region: 'Centre',
      city: 'Yaoundé',
      location: 'CAMTEL Zamengoe Datacenter, Yaoundé',
      work_mode: 'on-site' as const,
      duration_months: 6,
      start_date: '2026-10-20',
      end_date: '2027-04-20',
      deadline: '2026-10-10T23:59:59Z',
      is_paid: true,
      allowance_xaf: 120000,
      positions_available: 3,
      application_method: 'company_website' as const,
      application_url: 'https://careers.camtel.cm/internships/cloud-devops-2026',
      instructions: 'Click Apply on Company Website to register via CAMTEL’s verified institutional portal.',
      contact_email: 'datacenter@camtel.cm',
      is_featured: false,
      moderation_status: 'published' as const,
      created_at: '2026-08-15T00:00:00Z',
      updated_at: '2026-09-15T00:00:00Z',
      skills: ['Linux', 'Docker', 'Kubernetes', 'CI/CD', 'Bash', 'Networking'],
      requirements: [
        'Proficiency in Linux environments (Debian/RHEL/Ubuntu)',
        'Understanding of virtualization and container concepts',
        'Rigorous attention to system uptime and operational security',
      ],
      company: {
        id: 'comp_03',
        name: 'CAMTEL (Cameroon Telecommunications)',
        slug: 'camtel',
        logo_url: null,
        verification_status: 'verified',
        city: 'Yaoundé',
        region: 'Centre',
      },
    },
    {
      id: 'int_04',
      company_id: 'comp_04',
      title: 'Mobile Application Developer Intern (Flutter / React Native)',
      slug: 'mobile-app-developer-intern-activespaces',
      field_of_study_id: 'fld_mobile',
      specialization: 'Cross-Platform Mobile Apps & Offline-First Architectures',
      description:
        'Develop cutting-edge cross-platform mobile apps for fast-growing African digital services at ActiveSpaces. You will implement offline-first state synchronization, camera/GPS integrations, and sleek Material/Cupertino interfaces.',
      department: 'Mobile Engineering Labs',
      education_level: 'HND / BSc in Software Development or Computer Science',
      region: 'Littoral',
      city: 'Douala',
      location: 'ActiveSpaces Douala Akwa Hub',
      work_mode: 'hybrid' as const,
      duration_months: 3,
      start_date: '2026-10-01',
      end_date: '2026-12-31',
      deadline: '2026-09-30T23:59:59Z',
      is_paid: true,
      allowance_xaf: 100000,
      positions_available: 2,
      application_method: 'mantech' as const,
      application_url: null,
      instructions: 'Submit your GitHub profile link and mobile app demo apk or code sample.',
      contact_email: 'incubator@activespaces.com',
      is_featured: true,
      moderation_status: 'published' as const,
      created_at: '2026-08-20T00:00:00Z',
      updated_at: '2026-09-18T00:00:00Z',
      skills: ['Flutter', 'Dart', 'React Native', 'Mobile UI/UX', 'REST APIs'],
      requirements: [
        'Hands-on experience building at least 1 mobile app in Flutter or React Native',
        'Familiarity with state management (Riverpod, Bloc, or Redux/Zustand)',
        'Understanding of REST API integration and offline caching',
      ],
      company: {
        id: 'comp_04',
        name: 'ActiveSpaces Tech Innovation Hub',
        slug: 'activespaces',
        logo_url: null,
        verification_status: 'verified',
        city: 'Douala',
        region: 'Littoral',
      },
    },
    {
      id: 'int_05',
      company_id: 'comp_05',
      title: 'AI & Data Science Engineering Intern',
      slug: 'ai-data-science-intern-silicon-mountain',
      field_of_study_id: 'fld_ai',
      specialization: 'Machine Learning Models, NLP for Local Languages & Data Pipelines',
      description:
        'Work alongside experienced AI researchers in Buea. You will build and evaluate Natural Language Processing models, fine-tune open-weights LLMs for Cameroonian multilingual context, and construct robust automated data ingestion pipelines.',
      department: 'Artificial Intelligence & Data Engineering',
      education_level: 'BSc / Master in Data Science, AI or Computer Science',
      region: 'South-West',
      city: 'Buea',
      location: 'Silicon Mountain Tech Complex, Buea',
      work_mode: 'remote' as const,
      duration_months: 4,
      start_date: '2026-11-01',
      end_date: '2027-02-28',
      deadline: '2026-10-25T23:59:59Z',
      is_paid: true,
      allowance_xaf: 125000,
      positions_available: 2,
      application_method: 'external' as const,
      application_url: 'https://linkedin.com/jobs/view/silicon-mountain-ai-intern-2026',
      instructions: 'Apply externally via LinkedIn and confirm your application token in ManTech.',
      contact_email: 'ai.labs@siliconmountain.cm',
      is_featured: true,
      moderation_status: 'published' as const,
      created_at: '2026-08-25T00:00:00Z',
      updated_at: '2026-09-20T00:00:00Z',
      skills: ['Python', 'PyTorch', 'Pandas', 'Scikit-Learn', 'FastAPI', 'Data Cleaning'],
      requirements: [
        'Solid background in linear algebra, statistics, and machine learning theory',
        'Proficiency in Python and standard data science libraries',
        'Experience training or fine-tuning ML models',
      ],
      company: {
        id: 'comp_05',
        name: 'Silicon Mountain Buea Labs',
        slug: 'silicon-mountain-buea',
        logo_url: null,
        verification_status: 'verified',
        city: 'Buea',
        region: 'South-West',
      },
    },
  ] as unknown as Internship[],

  applications: [
    {
      id: 'app_01',
      student_id: 'usr_student_01',
      internship_id: 'int_01',
      status: 'internship_active' as const,
      cover_letter:
        'I am David Kamga, 3rd year Software Engineering student at University of Yaoundé I. I have actively built full-stack applications with Next.js, Prisma, and PostgreSQL. I look forward to contributing to MTN Cameroon’s digital enterprise division.',
      resume_url: 'https://mantech-nexus.cm/documents/david_kamga_cv.pdf',
      readiness_score: 95,
      created_at: '2026-08-05T10:00:00Z',
      updated_at: '2026-09-15T12:00:00Z',
      timelines: [
        { date: '05 Aug 2026', title: 'Application Submitted', desc: 'Candidate applied on MANTECH with readiness score 95%' },
        { date: '12 Aug 2026', title: 'Application Reviewed', desc: 'Shortlisted by Brenda Ngu (MTN Cameroon HR)' },
        { date: '20 Aug 2026', title: 'Technical Interview', desc: 'Passed technical coding session with 4.8/5 score' },
        { date: '28 Aug 2026', title: 'Placement Confirmed', desc: 'Placement agreement verified with ENSPY / UY1 faculty' },
        { date: '01 Sep 2026', title: 'Internship Active', desc: 'Eng. Martin Fon assigned as industry supervisor' },
      ],
    },
    {
      id: 'app_02',
      student_id: 'usr_student_01',
      internship_id: 'int_02',
      status: 'interview' as const,
      cover_letter:
        'Passionate about network security and SIEM threat monitoring. I have passed certified lab simulations and look forward to learning within Orange CyberDefense.',
      resume_url: 'https://mantech-nexus.cm/documents/david_kamga_cv.pdf',
      readiness_score: 90,
      created_at: '2026-08-15T14:00:00Z',
      updated_at: '2026-09-18T16:00:00Z',
      timelines: [
        { date: '15 Aug 2026', title: 'Application Submitted', desc: 'Direct application through MANTECH' },
        { date: '22 Aug 2026', title: 'Under Review', desc: 'Reviewed by Orange CyberDefense team' },
        { date: '18 Sep 2026', title: 'Interview Scheduled', desc: 'Online technical panel scheduled for 02 Oct 2026' },
      ],
    },
  ],

  placement: {
    id: 'plc_01',
    application_id: 'app_01',
    student_id: 'usr_student_01',
    company_id: 'comp_01',
    company_name: 'MTN Cameroon',
    internship_title: 'Full-Stack Software Engineering Intern',
    university_id: 'univ_01',
    university_name: 'University of Yaoundé I',
    supervisor_id: 'usr_supervisor_01',
    supervisor_name: 'Eng. Martin Fon',
    status: 'active' as const,
    health_status: 'healthy' as const,
    start_date: '2026-09-01',
    end_date: '2027-02-28',
    objectives:
      'Design enterprise microservices, integrate Neon PostgreSQL databases via Prisma ORM, implement secure Clerk RBAC, and deliver documented RESTful endpoints.',
    onboarding_checklist: [
      { id: 'ob_1', title: 'Placement Agreement Signed', completed: true },
      { id: 'ob_2', title: 'Company Access & VPN Setup', completed: true },
      { id: 'ob_3', title: 'Faculty Supervisor Assigned', completed: true },
      { id: 'ob_4', title: 'Sprint 1 Objectives Defined', completed: true },
      { id: 'ob_5', title: 'Security & Non-Disclosure Form', completed: true },
    ],
  },

  reports: [
    {
      id: 'rep_01',
      placement_id: 'plc_01',
      report_type: 'weekly' as const,
      week_number: 1,
      period_start: '2026-09-01',
      period_end: '2026-09-07',
      summary: 'Initial architecture onboarding and enterprise repo setup',
      activities:
        'Cloned internal services, configured Docker local environment, reviewed architecture standards, and set up CI/CD pipeline integration.',
      challenges: 'Configuring enterprise VPN routing across dual-stack network.',
      skills_applied: ['Git', 'Docker', 'Linux', 'Next.js'],
      status: 'approved',
      feedback: 'Excellent start David. Code style and documentation standards were thoroughly met.',
      supervisor_signature: 'Eng. Martin Fon',
      submitted_at: '2026-09-07T18:00:00Z',
    },
    {
      id: 'rep_02',
      placement_id: 'plc_01',
      report_type: 'weekly' as const,
      week_number: 2,
      period_start: '2026-09-08',
      period_end: '2026-09-14',
      summary: 'Database schema modeling and Prisma client integration',
      activities:
        'Constructed PostgreSQL schemas on Neon DB, implemented database migrations, and built REST server actions with strict Zod validation.',
      challenges: 'Optimizing foreign key cascades and multi-tenant isolation filters.',
      skills_applied: ['Prisma', 'PostgreSQL', 'Zod', 'TypeScript'],
      status: 'approved',
      feedback: 'Prisma queries demonstrate solid understanding of tenant isolation. Well done.',
      supervisor_signature: 'Eng. Martin Fon',
      submitted_at: '2026-09-14T17:30:00Z',
    },
    {
      id: 'rep_03',
      placement_id: 'plc_01',
      report_type: 'weekly' as const,
      week_number: 3,
      period_start: '2026-09-15',
      period_end: '2026-09-21',
      summary: 'Authentication guardrails and Role-Based Access Control',
      activities:
        'Integrated Clerk middleware route protection, built role validation helpers, and added security telemetry for audit logs.',
      challenges: 'Ensuring non-eligible roles cannot access Career Passport companion URLs.',
      skills_applied: ['Clerk', 'Next.js Middleware', 'Security RBAC', 'Audit Logging'],
      status: 'approved',
      feedback: 'Outstanding attention to security guardrails.',
      supervisor_signature: 'Eng. Martin Fon',
      submitted_at: '2026-09-21T19:00:00Z',
    },
  ],

  evaluations: [
    {
      id: 'eval_01',
      placement_id: 'plc_01',
      evaluator_name: 'Eng. Martin Fon',
      evaluator_role: 'Industry Supervisor (CAMTEL / MTN)',
      evaluation_type: 'supervisor',
      technical_score: 5,
      communication_score: 4,
      punctuality_score: 5,
      initiative_score: 5,
      overall_score: 5,
      qualitative_feedback:
        'David displays exceptional technical competence in modern TypeScript and full-stack software development. He actively collaborates with senior engineers and delivers robust, production-tested code.',
      recommendations: 'Continue expanding expertise into distributed message queues (Kafka/RabbitMQ).',
      submitted_at: '2026-09-22T10:00:00Z',
    },
  ],

  careerPassport: {
    id: 'pass_01',
    user_id: 'usr_student_01',
    passport_number: 'MTN-CM-2026-9814',
    headline: 'Full-Stack Software Engineer & Cloud Systems Specialist',
    bio: 'Verified IT Intern on ManTech Nexus. Specializing in Next.js, TypeScript, PostgreSQL, and scalable cloud architectures.',
    total_hours_completed: 320,
    completion_badge_issued: true,
    issued_at: '2026-09-25T12:00:00Z',
    achievements: [
      {
        id: 'ach_1',
        title: 'Verified Enterprise Software Internship',
        category: 'verified_internship',
        issuer: 'MTN Cameroon & ManTech Nexus',
        issue_date: 'September 2026',
        description: 'Successfully completed 320+ supervised engineering hours with 5/5 supervisor rating.',
        badge_color: 'bg-emerald-500',
      },
      {
        id: 'ach_2',
        title: 'Top 5% Student Readiness Honors',
        category: 'award',
        issuer: 'University of Yaoundé I & ENSPY',
        issue_date: 'August 2026',
        description: 'Achieved 95% readiness score across technical assessment, CV, and verified skills.',
        badge_color: 'bg-blue-600',
      },
      {
        id: 'ach_3',
        title: 'Cameroon National HND Excellence Nominee',
        category: 'certification',
        issuer: 'MINESUP Cameroon',
        issue_date: 'July 2026',
        description: 'Recognized for distinguished academic achievement in Software Engineering.',
        badge_color: 'bg-amber-500',
      },
    ],
    experiences: [
      {
        id: 'exp_1',
        company_name: 'MTN Cameroon',
        role_title: 'Full-Stack Software Engineering Intern',
        duration_months: 6,
        location: 'Douala, Cameroon (Hybrid)',
        skills_verified: ['TypeScript', 'Next.js', 'PostgreSQL', 'Prisma', 'REST APIs', 'Docker'],
        endorsement_comment:
          'Demonstrated exemplary technical capability and professional diligence on enterprise microservices.',
        supervisor_name: 'Eng. Martin Fon',
        verified_at: '2026-09-22',
      },
    ],
  } as CareerPassportProfile,

  auditLogs: [
    {
      id: 'log_01',
      actor_name: 'David Kamga',
      actor_role: 'student',
      action: 'APPLICATION_SUBMITTED',
      entity_type: 'internship_opportunity',
      entity_id: 'int_01',
      details: 'Applied to Full-Stack Software Engineering Intern at MTN Cameroon',
      created_at: '2026-08-05T10:00:00Z',
    },
    {
      id: 'log_02',
      actor_name: 'Brenda Ngu',
      actor_role: 'company',
      action: 'CANDIDATE_SHORTLISTED',
      entity_type: 'application',
      entity_id: 'app_01',
      details: 'Candidate David Kamga shortlisted for technical interview',
      created_at: '2026-08-12T11:30:00Z',
    },
    {
      id: 'log_03',
      actor_name: 'Eng. Martin Fon',
      actor_role: 'supervisor',
      action: 'LOGBOOK_REPORT_APPROVED',
      entity_type: 'internship_report',
      entity_id: 'rep_03',
      details: 'Week 3 Logbook report approved with commendation for RBAC security',
      created_at: '2026-09-21T19:00:00Z',
    },
    {
      id: 'log_04',
      actor_name: 'Manuel Tessoh (Admin)',
      actor_role: 'admin',
      action: 'COMPANY_VERIFIED',
      entity_type: 'company',
      entity_id: 'comp_01',
      details: 'MTN Cameroon corporate registration verified and badge issued',
      created_at: '2026-01-15T09:00:00Z',
    },
  ],
};
